### PR TITLE
fix(deps): add support for v8.0.5

### PR DESCRIPTION
**Pull request by overflw**

### CODE REVIEW

**Comment by overflw** [comment]
@qstokkink 
Could you verify whether this flatpak build supports all the features of the 8.0.5 version?

**Comment by qstokkink** [comment]
Looks like the test build failed: apart from the failure, it looks O.K.

I can have a better look when the test build passes.

**Comment by overflw** [comment]
@qstokkink fixed the issue - the test build can be installed now (:

**Comment by qstokkink** [comment]
Everything seems to work, except for the icon in the top right that is replaced with three dots:



I never got this to work in my own tests. So, I think this is working as good as it can work. 👍

**Pull request merged**
